server:
  port: 9999
  servlet:
    context-path: /conferencem

spring:

  datasource:
    name: test
    #url: jdbc:mysql://123.207.2.127:3306/cloudconference?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/cloudconference?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
    #password: xzit_Cp$Yz_0310_just
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatemetns: 20

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: xiaopeng
    timeout: 50000ms
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 50000ms

  servlet:
    multipart:
      max-file-size: 20Mb #单个文件大小限制

  # mongodb的配置
  data:
    mongodb:
      uri: mongodb://dev:123456@localhost:27017/just

# mybatis 的相关配置
mybatis:
  mapper-locations: classpath:mapping/*.xml # mybatis 映射文件
  type-aliases-package: com.justcs.entity # 对应实体类的路径


# pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 配置上传文件的临时地址
voiceupload:
  basetemp: /usr/upload



